//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LSOmni.DataAccess.BOConnection.PreCommon.SaveTermsAcceptance {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SaveTermsAcceptance_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance")]
    public partial class SaveTermsAcceptance : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallSaveTermsAcceptanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SaveTermsAcceptance() {
            this.Url = global::LSOmni.DataAccess.BOConnection.PreCommon.Properties.Settings.Default.LSOmni_DataAccess_BOConnection_PreCommon_SaveTermsAcceptance_SaveTermsAcceptance;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallSaveTermsAcceptanceCompletedEventHandler CallSaveTermsAcceptanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance:SaveTermsAcceptance", RequestElementName="SaveTermsAcceptance", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", ResponseElementName="SaveTermsAcceptance_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CallSaveTermsAcceptance(ref string responseCode, ref string errorText, RootSaveTermsAcceptance saveTermsAcceptanceXml) {
            object[] results = this.Invoke("CallSaveTermsAcceptance", new object[] {
                        responseCode,
                        errorText,
                        saveTermsAcceptanceXml});
            responseCode = ((string)(results[0]));
            errorText = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void CallSaveTermsAcceptanceAsync(string responseCode, string errorText, RootSaveTermsAcceptance saveTermsAcceptanceXml) {
            this.CallSaveTermsAcceptanceAsync(responseCode, errorText, saveTermsAcceptanceXml, null);
        }
        
        /// <remarks/>
        public void CallSaveTermsAcceptanceAsync(string responseCode, string errorText, RootSaveTermsAcceptance saveTermsAcceptanceXml, object userState) {
            if ((this.CallSaveTermsAcceptanceOperationCompleted == null)) {
                this.CallSaveTermsAcceptanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallSaveTermsAcceptanceOperationCompleted);
            }
            this.InvokeAsync("CallSaveTermsAcceptance", new object[] {
                        responseCode,
                        errorText,
                        saveTermsAcceptanceXml}, this.CallSaveTermsAcceptanceOperationCompleted, userState);
        }
        
        private void OnCallSaveTermsAcceptanceOperationCompleted(object arg) {
            if ((this.CallSaveTermsAcceptanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallSaveTermsAcceptanceCompleted(this, new CallSaveTermsAcceptanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x80048")]
    public partial class RootSaveTermsAcceptance {
        
        private SaveTermsAcceptance1[] saveTermsAcceptanceField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SaveTermsAcceptance")]
        public SaveTermsAcceptance1[] SaveTermsAcceptance {
            get {
                return this.saveTermsAcceptanceField;
            }
            set {
                this.saveTermsAcceptanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SaveTermsAcceptance", Namespace="urn:microsoft-dynamics-nav/xmlports/x80048")]
    public partial class SaveTermsAcceptance1 {
        
        private string accountIdField;
        
        private string deviceIdField;
        
        private string termsAndConditionsVersionField;
        
        private string privacyPolicyVersionField;
        
        /// <remarks/>
        public string accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string termsAndConditionsVersion {
            get {
                return this.termsAndConditionsVersionField;
            }
            set {
                this.termsAndConditionsVersionField = value;
            }
        }
        
        /// <remarks/>
        public string privacyPolicyVersion {
            get {
                return this.privacyPolicyVersionField;
            }
            set {
                this.privacyPolicyVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CallSaveTermsAcceptanceCompletedEventHandler(object sender, CallSaveTermsAcceptanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallSaveTermsAcceptanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallSaveTermsAcceptanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591