//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BOConnection.Bonus.SaveTermsAcceptance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", ConfigurationName="SaveTermsAcceptance.SaveTermsAcceptance_Port")]
    public interface SaveTermsAcceptance_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance:SaveTermsAcceptance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Result SaveTermsAcceptance(DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance1 request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance:SaveTermsAcceptance", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Result> SaveTermsAcceptanceAsync(DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x80048")]
    public partial class RootSaveTermsAcceptance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SaveTermsAcceptance[] saveTermsAcceptanceField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SaveTermsAcceptance", Order=0)]
        public SaveTermsAcceptance[] SaveTermsAcceptance {
            get {
                return this.saveTermsAcceptanceField;
            }
            set {
                this.saveTermsAcceptanceField = value;
                this.RaisePropertyChanged("SaveTermsAcceptance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x80048")]
    public partial class SaveTermsAcceptance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string deviceIdField;
        
        private string termsAndConditionsVersionField;
        
        private string privacyPolicyVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("accountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string termsAndConditionsVersion {
            get {
                return this.termsAndConditionsVersionField;
            }
            set {
                this.termsAndConditionsVersionField = value;
                this.RaisePropertyChanged("termsAndConditionsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string privacyPolicyVersion {
            get {
                return this.privacyPolicyVersionField;
            }
            set {
                this.privacyPolicyVersionField = value;
                this.RaisePropertyChanged("privacyPolicyVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveTermsAcceptance", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", IsWrapped=true)]
    public partial class SaveTermsAcceptance1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", Order=0)]
        public string responseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", Order=1)]
        public string errorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", Order=2)]
        public DataAccess.BOConnection.Bonus.SaveTermsAcceptance.RootSaveTermsAcceptance saveTermsAcceptanceXml;
        
        public SaveTermsAcceptance1() {
        }
        
        public SaveTermsAcceptance1(string responseCode, string errorText, DataAccess.BOConnection.Bonus.SaveTermsAcceptance.RootSaveTermsAcceptance saveTermsAcceptanceXml) {
            this.responseCode = responseCode;
            this.errorText = errorText;
            this.saveTermsAcceptanceXml = saveTermsAcceptanceXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveTermsAcceptance_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", IsWrapped=true)]
    public partial class SaveTermsAcceptance_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", Order=0)]
        public string responseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SaveTermsAcceptance", Order=1)]
        public string errorText;
        
        public SaveTermsAcceptance_Result() {
        }
        
        public SaveTermsAcceptance_Result(string responseCode, string errorText) {
            this.responseCode = responseCode;
            this.errorText = errorText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaveTermsAcceptance_PortChannel : DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveTermsAcceptance_PortClient : System.ServiceModel.ClientBase<DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Port>, DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Port {
        
        public SaveTermsAcceptance_PortClient() {
        }
        
        public SaveTermsAcceptance_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaveTermsAcceptance_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveTermsAcceptance_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveTermsAcceptance_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Result DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Port.SaveTermsAcceptance(DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance1 request) {
            return base.Channel.SaveTermsAcceptance(request);
        }
        
        public void SaveTermsAcceptance(ref string responseCode, ref string errorText, DataAccess.BOConnection.Bonus.SaveTermsAcceptance.RootSaveTermsAcceptance saveTermsAcceptanceXml) {
            DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance1 inValue = new DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance1();
            inValue.responseCode = responseCode;
            inValue.errorText = errorText;
            inValue.saveTermsAcceptanceXml = saveTermsAcceptanceXml;
            DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Result retVal = ((DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Port)(this)).SaveTermsAcceptance(inValue);
            responseCode = retVal.responseCode;
            errorText = retVal.errorText;
        }
        
        public System.Threading.Tasks.Task<DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance_Result> SaveTermsAcceptanceAsync(DataAccess.BOConnection.Bonus.SaveTermsAcceptance.SaveTermsAcceptance1 request) {
            return base.Channel.SaveTermsAcceptanceAsync(request);
        }
    }
}
